services:
  server-gameaction:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis-1
  postgres:
    image: 'postgres:latest'
    hostname: 'postgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    # ports:
    #   - '5432:5432'
  # rabbitmq:
  #   image: 'rabbitmq:latest'
  #   environment:
  #     - 'RABBITMQ_DEFAULT_PASS=secret'
  #     - 'RABBITMQ_DEFAULT_USER=myuser'
  #   ports:
  #     - '5672'
  redis-1:
    image: 'redis:latest'
    hostname: 'redis'
    ports:
      - '6379'